on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install flake8 and plugins from setup.py
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint with flake8
        run: flake8 . --isolated --exclude=.cache,.venv,.svn,CVS,.bzr,.hg,.git,__pycache__,.tox --max-line-length=120
